name: sprint3
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_iconpicker: ^3.2.4 
  http: ^0.13.3 
  intl: ^0.17.0
  flutter_launcher_icons: ^0.10.0
  flutter_map: ^4.0.0
  latlong2: ^0.8.2
  url_launcher: ^6.0.0

flutter_icons:
  image_path: "assets/images/iconApp.jpeg"
  ios: true
  remove_alpha_ios: true
  android: "launcher_icon"
  adaptive_icon_foreground: "assets/images/iconApp.jpeg"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:  
  uses-material-design: true

  assets:
    - assets/
    - assets/images/

  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa-Light.ttf
          weight: 300
        - asset: assets/fonts/Comfortaa-Regular.ttf
          weight: 400
        - asset: assets/fonts/Comfortaa-Medium.ttf
          weight: 500
        - asset: assets/fonts/Comfortaa-Semibold.ttf
          weight: 600
        - asset: assets/fonts/Comfortaa-Bold.ttf
          weight: 700